redisapp/config/routes.rb
Rails.application.routes.draw do
  get 'emails' => "emails#index"

  post 'emails/standard'
  post 'emails/delayed'

   root 'letters#index'
   resources :letters, only: [:index] do
     member do
      patch :upvote 
      patch :downvote
     end
   end
end

redisapp/app/models/letter.rb
require 'letter_redis_repository'
class Letter < ActiveRecord::Base
	def self.top_10
		ids = LetterRedisRepository.top
		where(id: ids).order(score: :desc)
	end
end

redisapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

redisapp/app/controllers/emails_controller.rb
class EmailsController < ApplicationController
	rescue_from Net::OpenTimeout, :with => :mail_not_sent

	def mail_not_sent
		redirect_to emails_path, notice: "Email not sent"
	end

  def index

  end

  def standard
  	SendMail.default_mail(recipients).deliver
  	AnotherMail.default_mail(recipients).deliver
  	redirect_to emails_path, notice: "Sent emial (standard)"
  end

  def delayed
  	SendMailWorker.perform_async("SendMail",recipients)
  	SendMailWorker.perform_async("AnotherMail",recipients)
  	redirect_to emails_path, notice: "Sent emial (delayed)"
  end

  private
  def recipients
  	["n.chandrakanth0@gmail.com","chandu@indiahikes.com"]
  end
end

redisapp/app/controllers/letters_controller.rb
class LettersController < ApplicationController
	def index
		@letters = Letter.all.limit(100)
	end

	def upvote
		@letter = Letter.find(params[:id])
		@letter.update_attribute(:score, @letter.score + 1)
		LetterRedisRepository.increment @letter
		MessageWorker.perform_async("Anonymous","hey hi #{@letter.name} is the upvoted", letters_url)

		redirect_to  letters_path, notice: "Upvoted Letter"
	end

	def downvote
		@letter = Letter.find(params[:id])
		@letter.update_attribute(:score, @letter.score - 1)
		LetterRedisRepository.decrement @letter
		MessageWorker.perform_async("Anonymous","hey hi #{@letter.name} is the downvoted", letters_url)
		redirect_to  letters_path, notice: "Downvoted Letter"
	end
end

redisapp/app/helpers/application_helper.rb
module ApplicationHelper
	def top_letters_cache_key
		"top-letters/" + Letter.maximum(:updated_at).to_i.to_s
	end
end

redisapp/app/helpers/emails_helper.rb
module EmailsHelper
end

redisapp/app/views/another_mail/default_mail.html.haml
Bye

redisapp/app/views/application/_top.html.erb
<h2>Top 10</h2>
<ol>
	<% Letter.top_10.each do |letter| %>
 		<li>
 			<%=letter.name %>
 			<small><%=letter.score %> </small>

 			<%=link_to raw("&uarr;"),upvote_letter_path(letter),method: :patch %>
 			<%=link_to raw("&darr;"),downvote_letter_path(letter),method: :patch %>
 		</li>
 		<% end %>
</ol>

redisapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Redisapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

redisapp/app/views/letters/index.html.erb
<h1> List of all letters</h1>

<div class="row">
	<div class="col-md-9">
	<ul>
		<%@letters.each do |letter| %>
			<li><%=letter.name %> <%= letter.score %></li>
		<% end %>
	</ul>
	</div>
	<div class="col-md-3">
		<%= render 'top' %>
	</div>
</div>

redisapp/app/views/send_mail/default_mail.html.haml
Hi